/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_single_line_comment = 1,
  sym_multi_line_comment = 2,
  sym_identifier = 3,
  anon_sym_DOLLAR = 4,
  sym_string = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  sym_integer = 8,
  sym_float = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  anon_sym_LBRACK = 12,
  anon_sym_COMMA = 13,
  anon_sym_RBRACK = 14,
  anon_sym_String = 15,
  anon_sym_UInt = 16,
  anon_sym_Int = 17,
  anon_sym_Float = 18,
  anon_sym_Enum = 19,
  anon_sym_AT = 20,
  anon_sym_COLON = 21,
  anon_sym_option = 22,
  anon_sym_section = 23,
  sym_source_file = 24,
  sym_localization_key = 25,
  sym_string_or_lkey = 26,
  sym_enum = 27,
  sym_enum_with_block = 28,
  sym_boolean = 29,
  sym_array = 30,
  sym_values = 31,
  sym_types = 32,
  sym_meta_field = 33,
  sym_field = 34,
  sym_option = 35,
  sym_section = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_enum_with_block_repeat1 = 38,
  aux_sym_array_repeat1 = 39,
  aux_sym_option_repeat1 = 40,
  aux_sym_section_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_single_line_comment] = "single_line_comment",
  [sym_multi_line_comment] = "multi_line_comment",
  [sym_identifier] = "identifier",
  [anon_sym_DOLLAR] = "$",
  [sym_string] = "string",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_String] = "String",
  [anon_sym_UInt] = "UInt",
  [anon_sym_Int] = "Int",
  [anon_sym_Float] = "Float",
  [anon_sym_Enum] = "Enum",
  [anon_sym_AT] = "meta_field_keyword",
  [anon_sym_COLON] = ":",
  [anon_sym_option] = "option_keyword",
  [anon_sym_section] = "section_keyword",
  [sym_source_file] = "source_file",
  [sym_localization_key] = "localization_key",
  [sym_string_or_lkey] = "string_or_lkey",
  [sym_enum] = "enum",
  [sym_enum_with_block] = "enum_with_block",
  [sym_boolean] = "boolean",
  [sym_array] = "array",
  [sym_values] = "values",
  [sym_types] = "types",
  [sym_meta_field] = "meta_field",
  [sym_field] = "field",
  [sym_option] = "option",
  [sym_section] = "section",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_enum_with_block_repeat1] = "enum_with_block_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_option_repeat1] = "option_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_single_line_comment] = sym_single_line_comment,
  [sym_multi_line_comment] = sym_multi_line_comment,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_string] = sym_string,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_UInt] = anon_sym_UInt,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_Float] = anon_sym_Float,
  [anon_sym_Enum] = anon_sym_Enum,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_option] = anon_sym_option,
  [anon_sym_section] = anon_sym_section,
  [sym_source_file] = sym_source_file,
  [sym_localization_key] = sym_localization_key,
  [sym_string_or_lkey] = sym_string_or_lkey,
  [sym_enum] = sym_enum,
  [sym_enum_with_block] = sym_enum_with_block,
  [sym_boolean] = sym_boolean,
  [sym_array] = sym_array,
  [sym_values] = sym_values,
  [sym_types] = sym_types,
  [sym_meta_field] = sym_meta_field,
  [sym_field] = sym_field,
  [sym_option] = sym_option,
  [sym_section] = sym_section,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_enum_with_block_repeat1] = aux_sym_enum_with_block_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_option_repeat1] = aux_sym_option_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_single_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multi_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_option] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_localization_key] = {
    .visible = true,
    .named = true,
  },
  [sym_string_or_lkey] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_with_block] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_values] = {
    .visible = true,
    .named = true,
  },
  [sym_types] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_field] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_with_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_option_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_type = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_type, 3},
  [3] =
    {field_name, 0},
  [4] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 4,
  [7] = 7,
  [8] = 3,
  [9] = 7,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 28,
  [39] = 32,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 18,
  [48] = 19,
  [49] = 20,
  [50] = 34,
  [51] = 21,
  [52] = 23,
  [53] = 41,
  [54] = 25,
  [55] = 24,
  [56] = 46,
  [57] = 43,
  [58] = 45,
  [59] = 31,
  [60] = 22,
  [61] = 61,
  [62] = 37,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 63,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 66,
  [74] = 64,
  [75] = 75,
  [76] = 67,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '"', 2,
        '#', 44,
        '$', 55,
        ',', 66,
        '-', 41,
        ':', 74,
        '@', 73,
        'E', 20,
        'F', 17,
        'I', 24,
        'S', 36,
        'U', 6,
        '[', 65,
        ']', 67,
        'f', 7,
        'o', 29,
        's', 10,
        't', 31,
        '{', 57,
        '}', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 44,
        '$', 55,
        '-', 41,
        '[', 65,
        ']', 67,
        'f', 47,
        't', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(56);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == ',') ADVANCE(66);
      if (lookahead == '@') ADVANCE(73);
      if (lookahead == ']') ADVANCE(67);
      if (lookahead == '{') ADVANCE(57);
      if (lookahead == '}') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(46);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'I') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 13:
      if (lookahead == 'g') ADVANCE(68);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(72);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(76);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(70);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_single_line_comment);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_single_line_comment);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_single_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_multi_line_comment);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_UInt);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_Int);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_Float);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_Enum);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_option);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_section);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_single_line_comment] = ACTIONS(3),
    [sym_multi_line_comment] = ACTIONS(3),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_UInt] = ACTIONS(1),
    [anon_sym_Int] = ACTIONS(1),
    [anon_sym_Float] = ACTIONS(1),
    [anon_sym_Enum] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_option] = ACTIONS(1),
    [anon_sym_section] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(72),
    [sym_section] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(40),
    [sym_single_line_comment] = ACTIONS(3),
    [sym_multi_line_comment] = ACTIONS(3),
    [anon_sym_section] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym_integer,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_localization_key,
    STATE(46), 1,
      sym_values,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [42] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym_integer,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_localization_key,
    STATE(61), 1,
      sym_values,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [84] = 11,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym_integer,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(18), 1,
      sym_localization_key,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_enum_with_block,
      sym_values,
    STATE(19), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [124] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym_integer,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_localization_key,
    STATE(56), 1,
      sym_values,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [166] = 11,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_DOLLAR,
    ACTIONS(33), 1,
      sym_string,
    ACTIONS(35), 1,
      sym_integer,
    ACTIONS(37), 1,
      sym_float,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    STATE(47), 1,
      sym_localization_key,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 2,
      sym_enum_with_block,
      sym_values,
    STATE(48), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [206] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym_integer,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_localization_key,
    STATE(61), 1,
      sym_values,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [248] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym_integer,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_localization_key,
    STATE(61), 1,
      sym_values,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [290] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym_integer,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_localization_key,
    STATE(61), 1,
      sym_values,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [332] = 11,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym_integer,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    STATE(18), 1,
      sym_localization_key,
    STATE(61), 1,
      sym_values,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [371] = 11,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_DOLLAR,
    ACTIONS(33), 1,
      sym_string,
    ACTIONS(35), 1,
      sym_integer,
    ACTIONS(37), 1,
      sym_float,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    STATE(44), 1,
      sym_values,
    STATE(47), 1,
      sym_localization_key,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [410] = 6,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      anon_sym_AT,
    ACTIONS(53), 1,
      anon_sym_option,
    ACTIONS(55), 1,
      anon_sym_section,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(13), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [433] = 6,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 1,
      anon_sym_AT,
    ACTIONS(62), 1,
      anon_sym_option,
    ACTIONS(65), 1,
      anon_sym_section,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(13), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [456] = 6,
    ACTIONS(51), 1,
      anon_sym_AT,
    ACTIONS(53), 1,
      anon_sym_option,
    ACTIONS(55), 1,
      anon_sym_section,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(13), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [479] = 5,
    ACTIONS(51), 1,
      anon_sym_AT,
    ACTIONS(53), 1,
      anon_sym_option,
    ACTIONS(55), 1,
      anon_sym_section,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(12), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [499] = 5,
    ACTIONS(51), 1,
      anon_sym_AT,
    ACTIONS(53), 1,
      anon_sym_option,
    ACTIONS(55), 1,
      anon_sym_section,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(14), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [519] = 5,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(27), 3,
      sym_meta_field,
      sym_field,
      aux_sym_option_repeat1,
  [538] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(76), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [551] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(78), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [564] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(80), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [577] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(82), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [590] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(84), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [603] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(86), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [616] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(88), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [629] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(90), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [642] = 3,
    STATE(75), 1,
      sym_types,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(92), 5,
      anon_sym_String,
      anon_sym_UInt,
      anon_sym_Int,
      anon_sym_Float,
      anon_sym_Enum,
  [657] = 5,
    ACTIONS(94), 1,
      sym_identifier,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(27), 3,
      sym_meta_field,
      sym_field,
      aux_sym_option_repeat1,
  [676] = 3,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(104), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [690] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(104), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
  [702] = 4,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(17), 3,
      sym_meta_field,
      sym_field,
      aux_sym_option_repeat1,
  [718] = 3,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(108), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [732] = 4,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(35), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [747] = 4,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_section,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(33), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [762] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(117), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [773] = 4,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(35), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [788] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(124), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [799] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(126), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [810] = 3,
    ACTIONS(128), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(104), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [823] = 4,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(35), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [838] = 4,
    ACTIONS(5), 1,
      anon_sym_section,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(33), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [853] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(134), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [864] = 4,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [878] = 3,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(39), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [890] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(141), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [900] = 4,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [914] = 4,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [928] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(76), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [938] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(78), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [948] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(80), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [958] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(117), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [968] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(82), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [978] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(86), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [988] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(134), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [998] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(90), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [1008] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(88), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [1018] = 4,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    ACTIONS(151), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1032] = 3,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    STATE(32), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [1044] = 4,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    ACTIONS(153), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1058] = 3,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      anon_sym_section,
  [1070] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(84), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [1080] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(139), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1089] = 2,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_section,
  [1098] = 2,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1106] = 2,
    ACTIONS(159), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1114] = 2,
    ACTIONS(161), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1122] = 2,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1130] = 2,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1138] = 2,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1146] = 2,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1154] = 2,
    ACTIONS(171), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1162] = 2,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1170] = 2,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1178] = 2,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1186] = 2,
    ACTIONS(179), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1194] = 2,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
  [1202] = 2,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_single_line_comment,
      sym_multi_line_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 124,
  [SMALL_STATE(6)] = 166,
  [SMALL_STATE(7)] = 206,
  [SMALL_STATE(8)] = 248,
  [SMALL_STATE(9)] = 290,
  [SMALL_STATE(10)] = 332,
  [SMALL_STATE(11)] = 371,
  [SMALL_STATE(12)] = 410,
  [SMALL_STATE(13)] = 433,
  [SMALL_STATE(14)] = 456,
  [SMALL_STATE(15)] = 479,
  [SMALL_STATE(16)] = 499,
  [SMALL_STATE(17)] = 519,
  [SMALL_STATE(18)] = 538,
  [SMALL_STATE(19)] = 551,
  [SMALL_STATE(20)] = 564,
  [SMALL_STATE(21)] = 577,
  [SMALL_STATE(22)] = 590,
  [SMALL_STATE(23)] = 603,
  [SMALL_STATE(24)] = 616,
  [SMALL_STATE(25)] = 629,
  [SMALL_STATE(26)] = 642,
  [SMALL_STATE(27)] = 657,
  [SMALL_STATE(28)] = 676,
  [SMALL_STATE(29)] = 690,
  [SMALL_STATE(30)] = 702,
  [SMALL_STATE(31)] = 718,
  [SMALL_STATE(32)] = 732,
  [SMALL_STATE(33)] = 747,
  [SMALL_STATE(34)] = 762,
  [SMALL_STATE(35)] = 773,
  [SMALL_STATE(36)] = 788,
  [SMALL_STATE(37)] = 799,
  [SMALL_STATE(38)] = 810,
  [SMALL_STATE(39)] = 823,
  [SMALL_STATE(40)] = 838,
  [SMALL_STATE(41)] = 853,
  [SMALL_STATE(42)] = 864,
  [SMALL_STATE(43)] = 878,
  [SMALL_STATE(44)] = 890,
  [SMALL_STATE(45)] = 900,
  [SMALL_STATE(46)] = 914,
  [SMALL_STATE(47)] = 928,
  [SMALL_STATE(48)] = 938,
  [SMALL_STATE(49)] = 948,
  [SMALL_STATE(50)] = 958,
  [SMALL_STATE(51)] = 968,
  [SMALL_STATE(52)] = 978,
  [SMALL_STATE(53)] = 988,
  [SMALL_STATE(54)] = 998,
  [SMALL_STATE(55)] = 1008,
  [SMALL_STATE(56)] = 1018,
  [SMALL_STATE(57)] = 1032,
  [SMALL_STATE(58)] = 1044,
  [SMALL_STATE(59)] = 1058,
  [SMALL_STATE(60)] = 1070,
  [SMALL_STATE(61)] = 1080,
  [SMALL_STATE(62)] = 1089,
  [SMALL_STATE(63)] = 1098,
  [SMALL_STATE(64)] = 1106,
  [SMALL_STATE(65)] = 1114,
  [SMALL_STATE(66)] = 1122,
  [SMALL_STATE(67)] = 1130,
  [SMALL_STATE(68)] = 1138,
  [SMALL_STATE(69)] = 1146,
  [SMALL_STATE(70)] = 1154,
  [SMALL_STATE(71)] = 1162,
  [SMALL_STATE(72)] = 1170,
  [SMALL_STATE(73)] = 1178,
  [SMALL_STATE(74)] = 1186,
  [SMALL_STATE(75)] = 1194,
  [SMALL_STATE(76)] = 1202,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_or_lkey, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_values, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localization_key, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_field, 4, 0, 2),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_with_block_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_with_block_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 7, 0, 2),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 5, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_with_block, 4, 0, 3),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 4),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_types, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [175] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_config(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "config",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
