/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_DOLLAR = 2,
  sym_string = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  sym_integer = 6,
  sym_float = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RBRACK = 12,
  anon_sym_String = 13,
  anon_sym_UInt = 14,
  anon_sym_Int = 15,
  anon_sym_Float = 16,
  anon_sym_Enum = 17,
  anon_sym_AT = 18,
  anon_sym_COLON = 19,
  anon_sym_option = 20,
  anon_sym_section = 21,
  sym_source_file = 22,
  sym_localization_key = 23,
  sym_string_or_lkey = 24,
  sym_enum = 25,
  sym_enum_with_block = 26,
  sym_boolean = 27,
  sym_array = 28,
  sym_values = 29,
  sym_types = 30,
  sym_meta_field = 31,
  sym_field = 32,
  sym_option = 33,
  sym_section = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_enum_with_block_repeat1 = 36,
  aux_sym_array_repeat1 = 37,
  aux_sym_option_repeat1 = 38,
  aux_sym_section_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_DOLLAR] = "$",
  [sym_string] = "string",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_String] = "String",
  [anon_sym_UInt] = "UInt",
  [anon_sym_Int] = "Int",
  [anon_sym_Float] = "Float",
  [anon_sym_Enum] = "Enum",
  [anon_sym_AT] = "@",
  [anon_sym_COLON] = ":",
  [anon_sym_option] = "option",
  [anon_sym_section] = "section",
  [sym_source_file] = "source_file",
  [sym_localization_key] = "localization_key",
  [sym_string_or_lkey] = "string_or_lkey",
  [sym_enum] = "enum",
  [sym_enum_with_block] = "enum_with_block",
  [sym_boolean] = "boolean",
  [sym_array] = "array",
  [sym_values] = "values",
  [sym_types] = "types",
  [sym_meta_field] = "meta_field",
  [sym_field] = "field",
  [sym_option] = "option",
  [sym_section] = "section",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_enum_with_block_repeat1] = "enum_with_block_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_option_repeat1] = "option_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_string] = sym_string,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_UInt] = anon_sym_UInt,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_Float] = anon_sym_Float,
  [anon_sym_Enum] = anon_sym_Enum,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_option] = anon_sym_option,
  [anon_sym_section] = anon_sym_section,
  [sym_source_file] = sym_source_file,
  [sym_localization_key] = sym_localization_key,
  [sym_string_or_lkey] = sym_string_or_lkey,
  [sym_enum] = sym_enum,
  [sym_enum_with_block] = sym_enum_with_block,
  [sym_boolean] = sym_boolean,
  [sym_array] = sym_array,
  [sym_values] = sym_values,
  [sym_types] = sym_types,
  [sym_meta_field] = sym_meta_field,
  [sym_field] = sym_field,
  [sym_option] = sym_option,
  [sym_section] = sym_section,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_enum_with_block_repeat1] = aux_sym_enum_with_block_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_option_repeat1] = aux_sym_option_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_option] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_section] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_localization_key] = {
    .visible = true,
    .named = true,
  },
  [sym_string_or_lkey] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_with_block] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_values] = {
    .visible = true,
    .named = true,
  },
  [sym_types] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_field] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_with_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_option_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_type = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_type, 3},
  [3] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 21,
  [37] = 37,
  [38] = 38,
  [39] = 30,
  [40] = 19,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 15,
  [46] = 23,
  [47] = 33,
  [48] = 16,
  [49] = 31,
  [50] = 50,
  [51] = 50,
  [52] = 37,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 58,
  [63] = 61,
  [64] = 59,
  [65] = 65,
  [66] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '"', 3,
        '$', 67,
        ',', 78,
        '-', 40,
        ':', 91,
        '@', 90,
        'E', 19,
        'F', 16,
        'I', 23,
        'S', 35,
        'U', 5,
        '[', 77,
        ']', 79,
        'f', 6,
        'o', 28,
        's', 9,
        't', 30,
        '{', 69,
        '}', 70,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '$') ADVANCE(67);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '[') ADVANCE(77);
      if (lookahead == ']') ADVANCE(79);
      if (lookahead == 'f') ADVANCE(43);
      if (lookahead == 't') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '$') ADVANCE(67);
      if (lookahead == 'E') ADVANCE(53);
      if (lookahead == 'F') ADVANCE(50);
      if (lookahead == 'I') ADVANCE(54);
      if (lookahead == 'S') ADVANCE(63);
      if (lookahead == 'U') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(68);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ',') ADVANCE(78);
      if (lookahead == '@') ADVANCE(90);
      if (lookahead == ']') ADVANCE(79);
      if (lookahead == '{') ADVANCE(69);
      if (lookahead == '}') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 5:
      if (lookahead == 'I') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 12:
      if (lookahead == 'g') ADVANCE(80);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(88);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(92);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(93);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(82);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_String);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_UInt);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_UInt);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_Int);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_Int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_Float);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_Float);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_Enum);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_Enum);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_option);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_section);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_UInt] = ACTIONS(1),
    [anon_sym_Int] = ACTIONS(1),
    [anon_sym_Float] = ACTIONS(1),
    [anon_sym_Enum] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_option] = ACTIONS(1),
    [anon_sym_section] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(57),
    [sym_section] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(38),
    [anon_sym_section] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      sym_string,
    ACTIONS(11), 1,
      sym_integer,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    STATE(15), 1,
      sym_localization_key,
    STATE(53), 1,
      sym_values,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(24), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [38] = 11,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      sym_string,
    ACTIONS(11), 1,
      sym_integer,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_RBRACK,
    STATE(15), 1,
      sym_localization_key,
    STATE(53), 1,
      sym_values,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(24), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [76] = 11,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      sym_string,
    ACTIONS(11), 1,
      sym_integer,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    STATE(15), 1,
      sym_localization_key,
    STATE(42), 1,
      sym_values,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(24), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [114] = 10,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_integer,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(27), 1,
      sym_string,
    STATE(41), 1,
      sym_values,
    STATE(45), 1,
      sym_localization_key,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(24), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [149] = 10,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      sym_string,
    ACTIONS(11), 1,
      sym_integer,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(15), 1,
      sym_localization_key,
    STATE(53), 1,
      sym_values,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(24), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_boolean,
      sym_array,
  [184] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      sym_string,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(15), 1,
      sym_localization_key,
    STATE(33), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_enum_with_block,
      sym_types,
    ACTIONS(31), 5,
      anon_sym_String,
      anon_sym_UInt,
      anon_sym_Int,
      anon_sym_Float,
      anon_sym_Enum,
  [210] = 6,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(27), 1,
      sym_string,
    ACTIONS(33), 1,
      sym_identifier,
    STATE(45), 1,
      sym_localization_key,
    STATE(47), 4,
      sym_string_or_lkey,
      sym_enum,
      sym_enum_with_block,
      sym_types,
    ACTIONS(35), 5,
      anon_sym_String,
      anon_sym_UInt,
      anon_sym_Int,
      anon_sym_Float,
      anon_sym_Enum,
  [236] = 5,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    ACTIONS(39), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_option,
    ACTIONS(43), 1,
      anon_sym_section,
    STATE(10), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [255] = 5,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(47), 1,
      anon_sym_AT,
    ACTIONS(50), 1,
      anon_sym_option,
    ACTIONS(53), 1,
      anon_sym_section,
    STATE(10), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [274] = 5,
    ACTIONS(39), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_option,
    ACTIONS(43), 1,
      anon_sym_section,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(10), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [293] = 4,
    ACTIONS(39), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_option,
    ACTIONS(43), 1,
      anon_sym_section,
    STATE(9), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [309] = 4,
    ACTIONS(39), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_option,
    ACTIONS(43), 1,
      anon_sym_section,
    STATE(11), 4,
      sym_meta_field,
      sym_option,
      sym_section,
      aux_sym_section_repeat1,
  [325] = 2,
    STATE(55), 1,
      sym_types,
    ACTIONS(58), 5,
      anon_sym_String,
      anon_sym_UInt,
      anon_sym_Int,
      anon_sym_Float,
      anon_sym_Enum,
  [336] = 1,
    ACTIONS(60), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [345] = 1,
    ACTIONS(62), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [354] = 4,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    ACTIONS(68), 1,
      anon_sym_AT,
    STATE(18), 3,
      sym_meta_field,
      sym_field,
      aux_sym_option_repeat1,
  [369] = 4,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(75), 1,
      anon_sym_AT,
    STATE(18), 3,
      sym_meta_field,
      sym_field,
      aux_sym_option_repeat1,
  [384] = 2,
    ACTIONS(78), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [394] = 1,
    ACTIONS(82), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
  [402] = 2,
    ACTIONS(84), 1,
      anon_sym_LBRACE,
    ACTIONS(86), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [412] = 3,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_AT,
    STATE(17), 3,
      sym_meta_field,
      sym_field,
      aux_sym_option_repeat1,
  [424] = 1,
    ACTIONS(88), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [432] = 1,
    ACTIONS(90), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
  [440] = 1,
    ACTIONS(86), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
  [448] = 1,
    ACTIONS(92), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
  [456] = 1,
    ACTIONS(94), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
  [464] = 1,
    ACTIONS(96), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
  [472] = 1,
    ACTIONS(98), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_AT,
  [480] = 3,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [491] = 1,
    ACTIONS(102), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [498] = 3,
    ACTIONS(104), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [509] = 1,
    ACTIONS(109), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [516] = 1,
    ACTIONS(111), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [523] = 3,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 1,
      anon_sym_section,
    STATE(35), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [534] = 2,
    ACTIONS(118), 1,
      anon_sym_LBRACE,
    ACTIONS(86), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [543] = 1,
    ACTIONS(120), 4,
      anon_sym_RBRACE,
      anon_sym_AT,
      anon_sym_option,
      anon_sym_section,
  [550] = 3,
    ACTIONS(3), 1,
      anon_sym_section,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    STATE(35), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [561] = 3,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [572] = 2,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      anon_sym_section,
  [580] = 1,
    ACTIONS(128), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [586] = 3,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_array_repeat1,
  [596] = 3,
    ACTIONS(21), 1,
      anon_sym_RBRACK,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_array_repeat1,
  [606] = 3,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_array_repeat1,
  [616] = 1,
    ACTIONS(60), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [622] = 1,
    ACTIONS(88), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [628] = 1,
    ACTIONS(109), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [634] = 1,
    ACTIONS(62), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [640] = 1,
    ACTIONS(102), 3,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_AT,
  [646] = 2,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(30), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [654] = 2,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(39), 2,
      sym_field,
      aux_sym_enum_with_block_repeat1,
  [662] = 1,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      anon_sym_section,
  [667] = 1,
    ACTIONS(139), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [672] = 1,
    ACTIONS(141), 1,
      sym_identifier,
  [676] = 1,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
  [680] = 1,
    ACTIONS(145), 1,
      sym_identifier,
  [684] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [688] = 1,
    ACTIONS(149), 1,
      sym_identifier,
  [692] = 1,
    ACTIONS(151), 1,
      anon_sym_COLON,
  [696] = 1,
    ACTIONS(153), 1,
      anon_sym_COLON,
  [700] = 1,
    ACTIONS(155), 1,
      sym_identifier,
  [704] = 1,
    ACTIONS(157), 1,
      sym_identifier,
  [708] = 1,
    ACTIONS(159), 1,
      sym_identifier,
  [712] = 1,
    ACTIONS(161), 1,
      anon_sym_COLON,
  [716] = 1,
    ACTIONS(163), 1,
      anon_sym_COLON,
  [720] = 1,
    ACTIONS(165), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 114,
  [SMALL_STATE(6)] = 149,
  [SMALL_STATE(7)] = 184,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 236,
  [SMALL_STATE(10)] = 255,
  [SMALL_STATE(11)] = 274,
  [SMALL_STATE(12)] = 293,
  [SMALL_STATE(13)] = 309,
  [SMALL_STATE(14)] = 325,
  [SMALL_STATE(15)] = 336,
  [SMALL_STATE(16)] = 345,
  [SMALL_STATE(17)] = 354,
  [SMALL_STATE(18)] = 369,
  [SMALL_STATE(19)] = 384,
  [SMALL_STATE(20)] = 394,
  [SMALL_STATE(21)] = 402,
  [SMALL_STATE(22)] = 412,
  [SMALL_STATE(23)] = 424,
  [SMALL_STATE(24)] = 432,
  [SMALL_STATE(25)] = 440,
  [SMALL_STATE(26)] = 448,
  [SMALL_STATE(27)] = 456,
  [SMALL_STATE(28)] = 464,
  [SMALL_STATE(29)] = 472,
  [SMALL_STATE(30)] = 480,
  [SMALL_STATE(31)] = 491,
  [SMALL_STATE(32)] = 498,
  [SMALL_STATE(33)] = 509,
  [SMALL_STATE(34)] = 516,
  [SMALL_STATE(35)] = 523,
  [SMALL_STATE(36)] = 534,
  [SMALL_STATE(37)] = 543,
  [SMALL_STATE(38)] = 550,
  [SMALL_STATE(39)] = 561,
  [SMALL_STATE(40)] = 572,
  [SMALL_STATE(41)] = 580,
  [SMALL_STATE(42)] = 586,
  [SMALL_STATE(43)] = 596,
  [SMALL_STATE(44)] = 606,
  [SMALL_STATE(45)] = 616,
  [SMALL_STATE(46)] = 622,
  [SMALL_STATE(47)] = 628,
  [SMALL_STATE(48)] = 634,
  [SMALL_STATE(49)] = 640,
  [SMALL_STATE(50)] = 646,
  [SMALL_STATE(51)] = 654,
  [SMALL_STATE(52)] = 662,
  [SMALL_STATE(53)] = 667,
  [SMALL_STATE(54)] = 672,
  [SMALL_STATE(55)] = 676,
  [SMALL_STATE(56)] = 680,
  [SMALL_STATE(57)] = 684,
  [SMALL_STATE(58)] = 688,
  [SMALL_STATE(59)] = 692,
  [SMALL_STATE(60)] = 696,
  [SMALL_STATE(61)] = 700,
  [SMALL_STATE(62)] = 704,
  [SMALL_STATE(63)] = 708,
  [SMALL_STATE(64)] = 712,
  [SMALL_STATE(65)] = 716,
  [SMALL_STATE(66)] = 720,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_or_lkey, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localization_key, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_types, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_values, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_with_block, 4, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_with_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_with_block_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_field, 4, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 7, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 5, 0, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [147] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_config(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "config",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
